### ISSUE TITLE
Not recognizing updated version?

### ISSUE THREAD

**Issue by TeraValia** [x-megaman/InfiniteFusionPreloaded#1]
Just downloaded this 2.0 version, however when i go to launch it, i still get the pop up that says "you need to run the latest version of the installer to proceed!" saying that i have 1.0.12 and now 2.0. attached is a screen grab. the application closes out immediately when i press ok. 
![spriteinstaller](https://github.com/x-megaman/InfiniteFusionPreloaded/assets/134769090/cb86dff4-670b-4545-ba3f-cb64ee014a22)

i hope there's a solution besides trying to reset computer or launch it offline... my internet is fickle and if i disconnect from this wifi i might not get it back for a week...

**Comment by TeraValia** [comment]
Update, i found a solution (work around?) i went into the config.json and saw that "configversion" was at 2.0, but the "version" was still at 1.0.12. i changed the version in the json and its launching normally.

**Comment by x-megaman** [comment]
Thank you for bringing up the issue. I had the installer being tested and I forgot to update the config version. I updated the download link to have the correct version number to fix this issue.
